### ISSUE TITLE
Database connection closed before results are fetched

### ISSUE THREAD

**Issue by dopas21** [sphinx-contrib/sqltable#18]
Thanks for updating the plugin also for SQLAlchemy >= 2.0! 

Currently, the results cannot be processed correctly for my SQL Server database. While the included example file (relying on SQLite) can be converted into an html page correctly, querying a SQL Server database produces a 

`sqlalchemy.exc.DBAPIError: (pyodbc.Error) ('HY010', '[HY010] [unixODBC][Driver Manager]Function sequence error (0) (SQLFetch)')`

I suspect that this is related to the fact that the database connection is closed after executing the SQL query, but before actually iterating over the returned cursor. While some databases fetch all results into memory by default, others maintain a server side cursor, see https://docs.sqlalchemy.org/en/20/core/connections.html#using-server-side-cursors-a-k-a-stream-results

**Comment by dhellmann** [comment]
The fix for this issue was released in version 2.1.1. https://pypi.org/project/sphinxcontrib.sqltable/2.1.1/
