### ISSUE TITLE
update package to cope with SQLAlchemy 2.0 syntax

### ISSUE THREAD

**Issue by getreideacker** [sphinx-contrib/sqltable#7]
The current implementation is not compatible with the syntax used in SQLAlchemy 2.0. As a consequence 

> engine.execute(query)

 would not work anymore.

**Comment by dhellmann** [comment]
Fixed by #8

**Comment by dhellmann** [comment]
The fix from @GabrielGaona is included in [version 2.1.0](https://pypi.org/project/sphinxcontrib.sqltable/2.1.0/)
